module.exports.AZ_CITIES = [
  "Bullhead City, AZ",
  "Casa Grande, AZ",
  "Chandler, AZ",
  "Flagstaff, AZ",
  "Gilbert, AZ",
  "Glendale, AZ",
  "Goodyear, AZ",
  "Green Valley, AZ",
  "Kingman, AZ",
  "Lake Havasu City, AZ",
  "Laveen, AZ",
  "Maricopa, AZ",
  "Mesa, AZ",
  "Peoria, AZ",
  "Phoenix, AZ",
  "Prescott, AZ",
  "Queen Creek, AZ",
  "San Tan Valley, AZ",
  "Scottsdale, AZ",
  "Sierra Vista, AZ",
  "Surprise, AZ",
  "Tempe, AZ",
  "Tolleson, AZ",
  "Tucson, AZ",
  "Yuma, AZ",
];

module.exports.OR_CITIES = [
  "Portland, OR",
  "Salem, OR",
  "Eugene, OR",
  "Gresham, OR",
  "Hillsboro, OR",
  "Beaverton, OR",
  "Bend, OR",
  "Medford, OR",
  "Springfield, OR",
  "Corvallis, OR",
  "Tigard, OR",
  "Albany, OR",
  "Keizer, OR",
  "Lake Oswego, OR",
  "Grants Pass, OR",
  "Oregon City, OR",
  "McMinnville, OR",
  "Redmond, OR",
  "Tualatin, OR",
  "West Linn, OR",
  "Woodburn, OR",
  "Forest Grove, OR",
  "Wilsonville, OR",
  "Newberg, OR",
  "Roseburg, OR",
  "Happy Valley, OR",
  "Klamath Falls, OR",
  "Ashland, OR",
  "Milwaukie, OR",
  "Sherwood, OR",
  "Central Point, OR",
  "Canby, OR",
  "Hermiston, OR",
  "Lebanon, OR",
  "Pendleton, OR",
  "Dallas, OR",
  "Coos Bay, OR",
  "Troutdale, OR",
  "The Dalles, OR",
  "St. Helens, OR",
  "La Grande, OR",
  "Cornelius, OR",
  "Gladstone, OR",
  "Sandy, OR",
  "Ontario, OR",
  "Newport, OR",
  "Silverton, OR",
  "Monmouth, OR",
  "Cottage Grove, OR",
  "Prineville, OR",
  "Independence, OR",
  "Astoria, OR",
  "Sweet Home, OR",
  "North Bend, OR",
  "Baker City, OR",
  "Eagle Point, OR",
  "Fairview, OR",
  "Molalla, OR",
  "Florence, OR",
  "Lincoln City, OR",
  "Stayton, OR",
  "Sutherlin, OR",
  "Hood River, OR",
  "Scappoose, OR",
  "Umatilla, OR",
  "Milton-Freewater, OR",
  "Madras, OR",
  "Seaside, OR",
  "Talent, OR",
  "Brookings, OR",
  "Sheridan, OR",
  "Junction City, OR",
  "Warrenton, OR",
  "Winston, OR",
  "Creswell, OR",
  "Tillamook, OR",
  "Veneta, OR",
];

module.exports.TX_CITIES = [
  "Houston, TX",
  "San Antonio, TX",
  "Dallas, TX",
  "Austin, TX",
  "Fort Worth, TX",
  "El Paso, TX",
  "Arlington, TX",
  "Corpus Christi, TX",
  "Plano, TX",
  "Laredo, TX",
  "Lubbock, TX",
  "Irving, TX",
  "Garland, TX",
  "Amarillo, TX",
  "Grand Prairie, TX",
  "Brownsville, TX",
  "McKinney, TX",
  "Frisco, TX",
  "Pasadena, TX",
  "Killeen, TX",
  "Mesquite, TX",
  "McAllen, TX",
  "Midland, TX",
  "Denton, TX",
  "Waco, TX",
  "Carrollton, TX",
  "Round Rock, TX",
  "Abilene, TX",
  "Pearland, TX",
  "Odessa, TX",
  "Sugar Land, TX",
  "Beaumont, TX",
  "Richardson, TX",
  "The Woodlands, TX",
  "College Station, TX",
  "Lewisville, TX",
  "Tyler, TX",
  "Wichita Falls, TX",
  "League City, TX",
  "Allen, TX",
  "San Angelo, TX",
  "Edinburg, TX",
  "Conroe, TX",
  "Bryan, TX",
  "Mission, TX",
  "Longview, TX",
  "Atascocita, TX",
  "New Braunfels, TX",
  "Pharr, TX",
  "Baytown, TX",
  "Flower Mound, TX",
  "Cedar Park, TX",
  "Temple, TX",
  "Missouri City, TX",
  "Georgetown, TX",
  "North Richland Hills, TX",
  "Mansfield, TX",
  "Victoria, TX",
  "Harlingen, TX",
  "Rowlett, TX",
  "San Marcos, TX",
  "Pflugerville, TX",
  "Spring, TX",
  "Euless, TX",
  "Port Arthur, TX",
  "Leander, TX",
  "Grapevine, TX",
  "DeSoto, TX",
  "Galveston, TX",
  "Wylie, TX",
  "Bedford, TX",
  "Texas City, TX",
  "Cedar Hill, TX",
  "Keller, TX",
  "Little Elm, TX",
  "Burleson, TX",
  "Haltom City, TX",
  "Rockwall, TX",
  "Channelview, TX",
  "The Colony, TX",
  "Kyle, TX",
  "Sherman, TX",
  "Coppell, TX",
  "Huntsville, TX",
  "Schertz, TX",
  "Weslaco, TX",
  "Friendswood, TX",
  "Duncanville, TX",
  "Lancaster, TX",
  "Farmers Branch, TX",
  "Hurst, TX",
  "Mission Bend, TX",
  "Rosenberg, TX",
  "San Juan, TX",
  "Texarkana, TX",
  "Del Rio, TX",
  "Lufkin, TX",
  "Waxahachie, TX",
  "La Porte, TX",
  "Deer Park, TX",
];
