module.exports.FL_CITIES = [
  "Alachua, FL",
  "Altamonte Springs, FL",
  "Apopka, FL",
  "Aventura, FL",
  "Bartow, FL",
  "Boca Raton, FL",
  "Bonita Springs, FL",
  "Boynton Beach, FL",
  "Bradenton, FL",
  "Brandon, FL",
  "Brooksville, FL",
  "Callaway, FL",
  "Cape Coral, FL",
  "Casselberry, FL",
  "Clearwater, FL",
  "Clermont, FL",
  "Cocoa, FL",
  "Coconut Creek, FL",
  "Coconut Grove, FL",
  "Cooper City, FL",
  "Coral Gables, FL",
  "Coral Springs, FL",
  "Crestview, FL",
  "Crystal River, FL",
  "Dade City, FL",
  "Davenport, FL",
  "Davie, FL",
  "Daytona Beach, FL",
  "Deerfield Beach, FL",
  "Defuniak Springs, FL",
  "Deland, FL",
  "Delray Beach, FL",
  "Deltona, FL",
  "Destin, FL",
  "Doral, FL",
  "Dunnellon, FL",
  "Edgewater, FL",
  "Estero, FL",
  "Fernandina Beach, FL",
  "Fleming Island, FL",
  "Florida City, FL",
  "Fort Lauderdale, FL",
  "Fort Myers, FL",
  "Fort Pierce, FL",
  "Ft Lauderdale, FL",
  "Ft. Walton Beach, FL",
  "Gainesville, FL",
  "Greenacres, FL",
  "Gulf Breeze, FL",
  "Haines City, FL",
  "Hallandale Beach, FL",
  "Hialeah, FL",
  "Hollywood, FL",
  "Homestead, FL",
  "Indian Harbour Beach, FL",
  "Inlet Beach, FL",
  "Inverness, FL",
  "Jacksonville Beach, FL",
  "Jacksonville, FL",
  "Jupiter, FL",
  "Key Biscayne, FL",
  "Key Largo, FL",
  "Key West, FL",
  "Kissimmee, FL",
  "Lady Lake, FL",
  "Lake City, FL",
  "Lake Mary, FL",
  "Lake Wales, FL",
  "Lake Worth, FL",
  "Lakeland, FL",
  "Lantana, FL",
  "Largo, FL",
  "Leesburg, FL",
  "Live Oak, FL",
  "Longwood, FL",
  "Loxahatchee, FL",
  "Lutz, FL",
  "Maitland, FL",
  "Marathon, FL",
  "Marco Island, FL",
  "Margate, FL",
  "Marianna, FL",
  "Mary Esther, FL",
  "Melbourne, FL",
  "Merritt Island, FL",
  "Miami Beach, FL",
  "Miami Gardens, FL",
  "Miami Lakes, FL",
  "Miami Shores, FL",
  "Miami Springs, FL",
  "Miami, FL",
  "Middleburg, FL",
  "Milton, FL",
  "Miramar, FL",
  "Mount Dora, FL",
  "Mulberry, FL",
  "Naples, FL",
  "Navarre, FL",
  "Neptune Beach, FL",
  "New Port Richey, FL",
  "New Smyrna Beach, FL",
  "Newberry, FL",
  "Niceville, FL",
  "Nokomis, FL",
  "North Lauderdale, FL",
  "North Miami Beach, FL",
  "North Miami, FL",
  "North Port, FL",
  "Ocala, FL",
  "Ocoee, FL",
  "Orange City, FL",
  "Orange Park, FL",
  "Orlando, FL",
  "Ormond Beach, FL",
  "Oviedo, FL",
  "Pace, FL",
  "Palatka, FL",
  "Palm Beach Gardens, FL",
  "Palm City, FL",
  "Palm Coast, FL",
  "Palm Harbor, FL",
  "Palm Springs, FL",
  "Panama City, FL",
  "Parrish, FL",
  "Pembroke Pines, FL",
  "Pensacola, FL",
  "Pinellas Park, FL",
  "Plant City, FL",
  "Plantation, FL",
  "Pompano Beach, FL",
  "Ponte Vedra, FL",
  "Port Charlotte, FL",
  "Port Orange, FL",
  "Port Richey, FL",
  "Port St Lucie, FL",
  "Port St. Lucie, FL",
  "Punta Gorda, FL",
  "Riverview, FL",
  "Royal Palm Beach, FL",
  "Ruskin, FL",
  "Saint Cloud, FL",
  "Saint Johns, FL",
  "Saint Petersburg, FL",
  "Sanford, FL",
  "Santa Rosa Beach, FL",
  "Sarasota, FL",
  "Sebastian, FL",
  "Sebring, FL",
  "Seminole, FL",
  "Spring Hill, FL",
  "St Petersburg, FL",
  "St. Augustine, FL",
  "St. Petersburg, FL",
  "Starke, FL",
  "Stuart, FL",
  "Sunny Isles Beach, FL",
  "Sunrise, FL",
  "Surfside, FL",
  "Tallahassee, FL",
  "Tampa, FL",
  "Tarpon Springs, FL",
  "Tavares, FL",
  "Tavernier, FL",
  "Temple Terrace, FL",
  "Tequesta, FL",
  "The Villages, FL",
  "Titusville, FL",
  "Trinity, FL",
  "Valrico, FL",
  "Venice, FL",
  "Vero Beach, FL",
  "Wellington, FL",
  "Wesley Chapel, FL",
  "West Melbourne, FL",
  "West Palm Beach, FL",
  "Weston, FL",
  "Windermere, FL",
  "Winter Garden, FL",
  "Winter Haven, FL",
  "Winter Park, FL",
  "Winter Springs, FL",
  "Yulee, FL",
  "Zephyrhills, FL",
];

module.exports.AZ_CITIES = [
  "Bullhead City, AZ",
  "Casa Grande, AZ",
  "Chandler, AZ",
  "Flagstaff, AZ",
  "Gilbert, AZ",
  "Glendale, AZ",
  "Goodyear, AZ",
  "Green Valley, AZ",
  "Kingman, AZ",
  "Lake Havasu City, AZ",
  "Laveen, AZ",
  "Maricopa, AZ",
  "Mesa, AZ",
  "Peoria, AZ",
  "Phoenix, AZ",
  "Prescott, AZ",
  "Queen Creek, AZ",
  "San Tan Valley, AZ",
  "Scottsdale, AZ",
  "Sierra Vista, AZ",
  "Surprise, AZ",
  "Tempe, AZ",
  "Tolleson, AZ",
  "Tucson, AZ",
  "Yuma, AZ",
];

module.exports.OR_CITIES = [
  "Portland, OR",
  "Salem, OR",
  "Eugene, OR",
  "Gresham, OR",
  "Hillsboro, OR",
  "Beaverton, OR",
  "Bend, OR",
  "Medford, OR",
  "Springfield, OR",
  "Corvallis, OR",
  "Tigard, OR",
  "Albany, OR",
  "Keizer, OR",
  "Lake Oswego, OR",
  "Grants Pass, OR",
  "Oregon City, OR",
  "McMinnville, OR",
  "Redmond, OR",
  "Tualatin, OR",
  "West Linn, OR",
  "Woodburn, OR",
  "Forest Grove, OR",
  "Wilsonville, OR",
  "Newberg, OR",
  "Roseburg, OR",
  "Happy Valley, OR",
  "Klamath Falls, OR",
  "Ashland, OR",
  "Milwaukie, OR",
  "Sherwood, OR",
  "Central Point, OR",
  "Canby, OR",
  "Hermiston, OR",
  "Lebanon, OR",
  "Pendleton, OR",
  "Dallas, OR",
  "Coos Bay, OR",
  "Troutdale, OR",
  "The Dalles, OR",
  "St. Helens, OR",
  "La Grande, OR",
  "Cornelius, OR",
  "Gladstone, OR",
  "Sandy, OR",
  "Ontario, OR",
  "Newport, OR",
  "Silverton, OR",
  "Monmouth, OR",
  "Cottage Grove, OR",
  "Prineville, OR",
  "Independence, OR",
  "Astoria, OR",
  "Sweet Home, OR",
  "North Bend, OR",
  "Baker City, OR",
  "Eagle Point, OR",
  "Fairview, OR",
  "Molalla, OR",
  "Florence, OR",
  "Lincoln City, OR",
  "Stayton, OR",
  "Sutherlin, OR",
  "Hood River, OR",
  "Scappoose, OR",
  "Umatilla, OR",
  "Milton-Freewater, OR",
  "Madras, OR",
  "Seaside, OR",
  "Talent, OR",
  "Brookings, OR",
  "Sheridan, OR",
  "Junction City, OR",
  "Warrenton, OR",
  "Winston, OR",
  "Creswell, OR",
  "Tillamook, OR",
  "Veneta, OR",
];

module.exports.TX_CITIES = [
  "Houston, TX",
  "San Antonio, TX",
  "Dallas, TX",
  "Austin, TX",
  "Fort Worth, TX",
  "El Paso, TX",
  "Arlington, TX",
  "Corpus Christi, TX",
  "Plano, TX",
  "Laredo, TX",
  "Lubbock, TX",
  "Irving, TX",
  "Garland, TX",
  "Amarillo, TX",
  "Grand Prairie, TX",
  "Brownsville, TX",
  "McKinney, TX",
  "Frisco, TX",
  "Pasadena, TX",
  "Killeen, TX",
  "Mesquite, TX",
  "McAllen, TX",
  "Midland, TX",
  "Denton, TX",
  "Waco, TX",
  "Carrollton, TX",
  "Round Rock, TX",
  "Abilene, TX",
  "Pearland, TX",
  "Odessa, TX",
  "Sugar Land, TX",
  "Beaumont, TX",
  "Richardson, TX",
  "The Woodlands, TX",
  "College Station, TX",
  "Lewisville, TX",
  "Tyler, TX",
  "Wichita Falls, TX",
  "League City, TX",
  "Allen, TX",
  "San Angelo, TX",
  "Edinburg, TX",
  "Conroe, TX",
  "Bryan, TX",
  "Mission, TX",
  "Longview, TX",
  "Atascocita, TX",
  "New Braunfels, TX",
  "Pharr, TX",
  "Baytown, TX",
  "Flower Mound, TX",
  "Cedar Park, TX",
  "Temple, TX",
  "Missouri City, TX",
  "Georgetown, TX",
  "North Richland Hills, TX",
  "Mansfield, TX",
  "Victoria, TX",
  "Harlingen, TX",
  "Rowlett, TX",
  "San Marcos, TX",
  "Pflugerville, TX",
  "Spring, TX",
  "Euless, TX",
  "Port Arthur, TX",
  "Leander, TX",
  "Grapevine, TX",
  "DeSoto, TX",
  "Galveston, TX",
  "Wylie, TX",
  "Bedford, TX",
  "Texas City, TX",
  "Cedar Hill, TX",
  "Keller, TX",
  "Little Elm, TX",
  "Burleson, TX",
  "Haltom City, TX",
  "Rockwall, TX",
  "Channelview, TX",
  "The Colony, TX",
  "Kyle, TX",
  "Sherman, TX",
  "Coppell, TX",
  "Huntsville, TX",
  "Schertz, TX",
  "Weslaco, TX",
  "Friendswood, TX",
  "Duncanville, TX",
  "Lancaster, TX",
  "Farmers Branch, TX",
  "Hurst, TX",
  "Mission Bend, TX",
  "Rosenberg, TX",
  "San Juan, TX",
  "Texarkana, TX",
  "Del Rio, TX",
  "Lufkin, TX",
  "Waxahachie, TX",
  "La Porte, TX",
  "Deer Park, TX",
];
