module.exports.AZ_CITIES = [
  "Bullhead City, AZ",
  "Casa Grande, AZ",
  "Chandler, AZ",
  "Flagstaff, AZ",
  "Gilbert, AZ",
  "Glendale, AZ",
  "Goodyear, AZ",
  "Green Valley, AZ",
  "Kingman, AZ",
  "Lake Havasu City, AZ",
  "Laveen, AZ",
  "Maricopa, AZ",
  "Mesa, AZ",
  "Peoria, AZ",
  "Phoenix, AZ",
  "Prescott, AZ",
  "Queen Creek, AZ",
  "San Tan Valley, AZ",
  "Scottsdale, AZ",
  "Sierra Vista, AZ",
  "Surprise, AZ",
  "Tempe, AZ",
  "Tolleson, AZ",
  "Tucson, AZ",
  "Yuma, AZ",
];

module.exports.OR_CITIES = [
  "Portland, OR",
  "Salem, OR",
  "Eugene, OR",
  "Gresham, OR",
  "Hillsboro, OR",
  "Beaverton, OR",
  "Bend, OR",
  "Medford, OR",
  "Springfield, OR",
  "Corvallis, OR",
  "Tigard, OR",
  "Albany, OR",
  "Keizer, OR",
  "Lake Oswego, OR",
  "Grants Pass, OR",
  "Oregon City, OR",
  "McMinnville, OR",
  "Redmond, OR",
  "Tualatin, OR",
  "West Linn, OR",
  "Woodburn, OR",
  "Forest Grove, OR",
  "Wilsonville, OR",
  "Newberg, OR",
  "Roseburg, OR",
  "Happy Valley, OR",
  "Klamath Falls, OR",
  "Ashland, OR",
  "Milwaukie, OR",
  "Sherwood, OR",
  "Central Point, OR",
  "Canby, OR",
  "Hermiston, OR",
  "Lebanon, OR",
  "Pendleton, OR",
  "Dallas, OR",
  "Coos Bay, OR",
  "Troutdale, OR",
  "The Dalles, OR",
  "St. Helens, OR",
  "La Grande, OR",
  "Cornelius, OR",
  "Gladstone, OR",
  "Sandy, OR",
  "Ontario, OR",
  "Newport, OR",
  "Silverton, OR",
  "Monmouth, OR",
  "Cottage Grove, OR",
  "Prineville, OR",
  "Independence, OR",
  "Astoria, OR",
  "Sweet Home, OR",
  "North Bend, OR",
  "Baker City, OR",
  "Eagle Point, OR",
  "Fairview, OR",
  "Molalla, OR",
  "Florence, OR",
  "Lincoln City, OR",
  "Stayton, OR",
  "Sutherlin, OR",
  "Hood River, OR",
  "Scappoose, OR",
  "Umatilla, OR",
  "Milton-Freewater, OR",
  "Madras, OR",
  "Seaside, OR",
  "Talent, OR",
  "Brookings, OR",
  "Sheridan, OR",
  "Junction City, OR",
  "Warrenton, OR",
  "Winston, OR",
  "Creswell, OR",
  "Tillamook, OR",
  "Veneta, OR",
];
